### ISSUE TITLE
Can you please provide images the demo scripts require?

### ISSUE THREAD

**Issue by SoftologyPro** [google/style-aligned#15]
They fail to start due to missing images like A.png, camel.jpg etc.
Can you update the example_images directory with these images?
Thanks.

**Comment by amirhertz** [comment]
Done.
Thanks

**Comment by pedropaf** [comment]
Hi, a few images are still missing from the controlnet example: 

- 'example_image/A.png'
- 'example_image/whale.png'
- 'example_image/camel.jpg'

It'd be great if you could add them. Thanks!

**Comment by SoftologyPro** [comment]
Still complains about missing train.jpg
